name: End-to-end tests 🧪
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn dev
  
  deploy:
    runs-on: ubuntu-20.04
    needs: [cypress-run]
    if: ${{ needs.cypress-run.result == 'success' }}
    steps:
      - name: Install Vercel CLI
        run: |
          npm install -g vercel

      - name: Deploy to Vercel
        run: |
          yarn build
          vercel --prod